// This file is generated by Velite

import config from '../../../velite.config'

type Collections = typeof config.collections

export type Lab = Collections['labs']['schema']['_output']
export declare const labs: Lab[]
